options {
    directory "/var/cache/bind";

    recursion yes;
    allow-query { any; };
    allow-recursion {
        127.0.0.1;
        192.168.3.0/24;
        192.168.30.0/24;
        192.168.40.0/24;
        10.8.0.0/24;
        10.200.0.0/30;
    };

    forwarders {
        8.8.8.8;
        1.1.1.1;
    };

    dnssec-validation no;
    listen-on { any; };
    listen-on-v6 { none; };
};

zone "lafassonnade.lan" {
    type master;
    file "/etc/bind/zones/db.lafassonnade.lan";
};

zone "3.168.192.in-addr.arpa" {
    type master;
    file "/etc/bind/zones/db.192.168.3";
};

zone "30.168.192.in-addr.arpa" {
    type master;
    file "/etc/bind/zones/db.192.168.30";
};

zone "40.168.192.in-addr.arpa" {
    type master;
    file "/etc/bind/zones/db.192.168.40";
};
