FROM docker:27-cli

RUN apk add --no-cache \
    bash \
    bind-tools \
    ca-certificates \
    curl \
    iproute2 \
    iputils \
    jq \
    less \
    netcat-openbsd \
    nmap \
    openldap-clients \
    openssl \
    tcpdump \
    traceroute \
    vim

WORKDIR /workspace

CMD ["sleep", "infinity"]
