# Généré automatiquement par vault-init.sh — NE PAS ÉDITER MANUELLEMENT
# WireGuard — R_ent3b (client) | LAN: 192.168.3.253

[Interface]
Address    = 10.200.0.2/30
PrivateKey = UO69cghR2E+BJfD36YqYSBnwd1b+Wp3TuqIYz6C2uH8=

PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s 192.168.3.4/32 -o wg0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s 192.168.3.4/32 -o wg0 -j MASQUERADE

[Peer]
# R_ent3a — Site Entreprise 3a
PublicKey    = C6j8FegGP5dph6Q0nrqtQyv9/QK+z++n43DPy1sNb0s=
PresharedKey = 1cWshNrpe+aHiISJER/ZiwL6gr6MK1gtUkAKebp2XUk=
AllowedIPs   = 10.200.0.1/32, 192.168.3.0/24
Endpoint     = 120.0.48.2:51820
PersistentKeepalive = 25
