# Généré automatiquement par vault-init.sh — NE PAS ÉDITER MANUELLEMENT
# WireGuard — R_ent3a (serveur) | WAN: 120.0.48.2 | LAN: 192.168.3.254

[Interface]
Address    = 10.200.0.1/30
PrivateKey = oH8NLKJZBIGUakwd3PQeEs1RT4gJqHrHc35xXzUYn2s=
ListenPort = 51820

PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s 192.168.3.0/24 -o eth1 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s 192.168.3.0/24 -o eth1 -j MASQUERADE

[Peer]
# R_ent3b — Site Entreprise 3b
PublicKey    = haoDVNMGRZACnqTMayr7qypds+rgyLPVvfiBNcKuM18=
PresharedKey = 1cWshNrpe+aHiISJER/ZiwL6gr6MK1gtUkAKebp2XUk=
AllowedIPs   = 10.200.0.2/32, 192.168.3.4/32
Endpoint     = 120.0.48.1:51821
PersistentKeepalive = 25
