; =============================================================================
; asterisk.conf — Configuration principale Asterisk
; Site Entreprise 3a | voip.lafassonnade.lan (192.168.3.3)
; =============================================================================

[options]
verbose = 3
debug = 0
nofork = yes                    ; Reste au premier plan (Docker)
quiet = no
timestamp = yes
execincludes = yes
dontwarn = yes
languageprefix = yes
defaultlanguage = fr

[directories]
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /var/lib/asterisk
astagidir => /var/lib/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /var/run/asterisk
astlogdir => /var/log/asterisk
astsbindir => /usr/sbin
